manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmk
      url-base: https://github.com/zmkfirmware/zmk
    - name: ncs
      url-base: https://github.com/nrfconnect/sdk-nrf
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: nrf
      remote: ncs
      revision: v2.4.0
    - name: nrfx
      remote: ncs
      revision: v2.4.0
  self:
    path: config
